// GENERATED by tools/gen-console-build-id.mjs — do not edit by hand.
//
// The id of the console build this module graph belongs to. A page compares it against
// console/VERSION.json, fetched with no-store, to detect a stale cached graph (#418).
export const CONSOLE_BUILD_ID = 'df9061de98a18f0d64527f23cad46ee5'
